export const mainActionTypes = {
  SET_TOKEN: 'SET_TOKEN',
  GET_SUBCRIPTION: 'GET_SUBCRIPTION',
  GET_EVENTS_DATA: 'GET_EVENTS_DATA',
  SET_EVENT_API_STATUS: 'SET_EVENT_API_STATUS',
  RESET_VALUES: 'RESET_VALUES',
};
